### ISSUE TITLE
Subscription Plan Name

### ISSUE THREAD

**Issue by NicolJamie** [RedRockDigital/rrd-ui#44]
We need to update the plan name from "default".

I've added a `friendly_tier_name` to the Subscriptions API route you can use. An example of the payload is below -- If we can use this going forward.

```
{
    "data": {
        "id": 3,
        "name": "default",
        "price": null,
        "status": "active",
        "next_payment_date": null,
        "is_trial": false,
        "trial_end": null,
        "tier": "Free",
        "friendly_tier_name": "Free",
        "allowances": {
            "submissions": 50
        }
    }
}
```

**Comment by thomaspalmer** [comment]
@NicolJamie we need to merge in changes from boilerplate on the FE.
