### ISSUE TITLE
Payments Update Card Fail

### ISSUE THREAD

**Issue by NicolJamie** [RedRockDigital/rrd-ui#46]
I am currently getting the following error when I click "Update Payment Details", it also just goes to a white screen?

![Screenshot 2023-01-28 at 19 31 39](https://user-images.githubusercontent.com/9093552/215287289-28c1adb8-9080-45ee-a320-3b25e9466dd2.png)

**Comment by thomaspalmer** [comment]
@NicolJamie we need to merge in changes from boilerplate on the FE.
